---
title: "Clustering"
author: "Juan Lucas García Osorio, Daniel Jose Forero y Sebastián Suárez García"
date: "11/24/2021"
output: html_document
---

Se carga el dataset.
```{r}
datos = read.csv('test.csv',sep = ",")
datos2 = read.csv('test.csv',sep = ",")
datos = datos[4:49]
#head(datos)
```

## Cluster jerarquico.


Datos escalados.

```{r}
data.scaled <- scale(x = datos, center = TRUE, scale = TRUE)
head(data.scaled)
```

Matriz de distancias

```{r}
require(stats)
# Matriz de distancias
res.dist = dist(x = data.scaled, method = "euclidean")
# Imprimir la matriz de distancias
output = as.matrix(res.dist)[1:6, 1:6]
round(output, digits = 3)

d = as.dist(output)
d
```

Agrupacion jerarquica


Dendograma.
```{r}
require(factoextra)
require(stats)
res.hc <- hclust(d = res.dist,method = "complete")
fviz_dend(x = res.hc, cex = 0.8, lwd = 0.8, k = 6, k_colors = c("jco"), rect = TRUE, rect_border = "jco", rect_fill = TRUE)

```

Cluster jerarquico con proyeccion PCA
```{r}
library(factoextra)
require(stats)
res.hc <- hclust(d = res.dist,method = "complete")
fviz_cluster(object = list(data=datos, cluster=cutree(res.hc, k=20)),
             ellipse.type = "convex", repel = TRUE, show.clust.cent = FALSE,
             labelsize = 8)  +
  labs(title = "Hierarchical clustering + Proyección PCA",
       subtitle = "Distancia euclídea, Lincage complete, K=20") +
  theme_bw() +
  theme(legend.position = "bottom")
```

Grafica similar a la de PCA, pero agrupandolos...
